abbr -a --set-cursor ad 'age --decrypt --identity ~/.age/%'
abbr -a --set-cursor lc 'curl http://$TAILSCALE_IPV4:3000/%'
abbr -a --set-cursor mrm 'rm -rf ~/.local/share/mise/installs/%'
abbr -a 7z 7zz
abbr -a a2 'aria2c -x8 -s8'
abbr -a ae 'age --encrypt --armor --recipients-file ~/.age/recipients'
abbr -a ag agy
abbr -a b bunnylol
abbr -a ba 'bundle add'
abbr -a bad 'bundle add --group development'
abbr -a bb 'bun run build'
abbr -a be 'bundle exec'
abbr -a bi 'bundle init'
abbr -a bl 'bun run lint'
abbr -a br brew
abbr -a brana 'brew analytics'
abbr -a brcat 'brew cat'
abbr -a brcle 'brew cleanup'
abbr -a brcom 'brew command'
abbr -a brcoms 'brew commands'
abbr -a brcon 'brew config'
abbr -a brdep 'brew deps'
abbr -a brdes 'brew desc'
abbr -a brdiy 'brew diy'
abbr -a brdoc 'brew doctor'
abbr -a brfet 'brew fetch'
abbr -a brgis 'brew gist-logs'
abbr -a brhom 'brew home'
abbr -a brinf 'brew info'
abbr -a brins 'brew install'
abbr -a brlea 'brew leaves'
abbr -a brlis 'brew list'
abbr -a brln 'brew ln'
abbr -a brlog 'brew log'
abbr -a brmig 'brew migrate'
abbr -a brmis 'brew missing'
abbr -a broca 'brew --cache'
abbr -a broce 'brew --cellar'
abbr -a broen 'brew --env'
abbr -a bropr 'brew --prefix'
abbr -a bropt 'brew options'
abbr -a brore 'brew --repository'
abbr -a brout 'brew outdated'
abbr -a brove 'brew --version'
abbr -a brpin 'brew pin'
abbr -a brpos 'brew postinstall'
abbr -a brpru 'brew prune'
abbr -a brrea 'brew readall'
abbr -a brrei 'brew reinstall'
abbr -a brs 'rm -rf node_modules bun.lock ; bun install'
abbr -a brse 'brew services'
abbr -a brsea 'brew search'
abbr -a brseli 'brew services list'
abbr -a brsh 'brew sh'
abbr -a brsty 'brew style'
abbr -a brswi 'brew switch'
abbr -a brtap 'brew tap'
abbr -a brtapi 'brew tap-info'
abbr -a brtapp 'brew tap-pin'
abbr -a brtapu 'brew tap-unpin'
abbr -a bru 'bun run'
abbr -a bruin 'brew uninstall'
abbr -a bruli 'brew unlink'
abbr -a brupa 'brew unpack'
abbr -a brupd 'brew update'
abbr -a brupdr 'brew update-reset'
abbr -a brupg 'brew upgrade'
abbr -a brupgg 'brew upgrade --greedy'
abbr -a brupi 'brew unpin'
abbr -a bruse 'brew uses'
abbr -a bruta 'brew untap'
abbr -a bs 'bun start'
abbr -a bt 'bun run typecheck'
abbr -a bund 'bun dev'
abbr -a buni 'bun install'
abbr -a bunr 'bun run'
abbr -a c cargo
abbr -a cf 'cd $HOME/.config/fish'
abbr -a ci 'cargo install'
abbr -a cl claude
abbr -a cm chezmoi
abbr -a cme 'chezmoi edit'
abbr -a cmea 'chezmoi edit --apply'
abbr -a cmeaf 'chezmoi edit --apply ~/.config/fish/'
abbr -a cmeam 'chezmoi edit --apply ~/.config/mise/config.toml'
abbr -a cmeas 'chezmoi edit --apply ~/.config/fish/secrets.fish'
abbr -a cmp 'chezmoi apply'
abbr -a cmr 'chezmoi re-add'
abbr -a cmu 'chezmoi update'
abbr -a cr 'cargo run'
abbr -a cs 'codesign --force --sign "Developer ID Application: David Williams"'
abbr -a cu cursor
abbr -a curls 'curl --proto-default https'
abbr -a cx 'codex --approval-mode full-auto'
abbr -a d docker
abbr -a dbt 'docker build -t'
abbr -a dc docker-compose
abbr -a dcd 'docker compose down'
abbr -a dcu 'docker compose up'
abbr -a de 'docker exec'
abbr -a dei 'docker exec -it'
abbr -a dev devcontainer
abbr -a di 'docker images'
abbr -a dp 'docker pull'
abbr -a dpa 'docker ps -a'
abbr -a dr 'docker run'
abbr -a dri 'docker run -it'
abbr -a drm 'docker rm'
abbr -a drmi 'docker rmi'
abbr -a ef '$EDITOR ~/.config/fish'
abbr -a emise 'chezmoi edit ~/.config/mise/config.toml'
abbr -a fl 'open -a ForkLift'
abbr -a fp 'git fetch --all --prune --tags --prune-tags --recurse-submodules=yes && git pull --all --prune --rebase'
abbr -a g gcloud
abbr -a ga 'git aa'
abbr -a gaa 'git aa'
abbr -a gb 'git branch'
abbr -a gc 'git clone'
abbr -a gcam 'git cam'
abbr -a gco 'git checkout'
abbr -a gd 'git diff'
abbr -a genderbase 'cd $HOME/src/github.com/daveio/genderbase'
abbr -a gf 'git fetch'
abbr -a gfci 'git -c core.editor="fast-conventional editor" commit'
abbr -a gl glooctl
abbr -a glog 'git log'
abbr -a gp 'git p'
abbr -a gpum 'git p -u origin main'
abbr -a gpums 'git p -u origin master'
abbr -a grm 'git rm'
abbr -a gst 'git status'
abbr -a h helm
abbr -a i 'bun x @modelcontextprotocol/inspector'
abbr -a inspector 'bun x @modelcontextprotocol/inspector'
abbr -a j just
abbr -a k kubectl
abbr -a ka 'kubectl apply'
abbr -a kg 'kubectl get'
abbr -a kgp 'kubectl get pod'
abbr -a kn1 'ssh -p212 dave@10.23.23.100'
abbr -a kn1j 'ssh -J dave@10.0.101.10:212 dave@10.23.23.100'
abbr -a kpf 'kubectl port-forward'
abbr -a l linkerd
abbr -a lic 'licenser -n "Dave Williams" -e "dave@dave.io" -l mit'
abbr -a lics 'cd $LICS'
abbr -a loop 'adb -s adb-GNFMGBD3PAA000011-FVqS8U._adb-tls-connect._tcp'
abbr -a loop-local 'adb -s GNFMGBD3PAA000011'
abbr -a ls 'eza --icons=always --hyperlink --git --git-repos --group-directories-first -O'
abbr -a m mise
abbr -a ma 'open -a Marked'
abbr -a marked 'open -a Marked'
abbr -a marksafe 'xattr -d com.apple.quarantine'
abbr -a mcsv 'open -a Modern\ CSV'
abbr -a md 'mise dev'
abbr -a me 'open -a MarkEdit'
abbr -a mi 'mise i'
abbr -a mk minikube
abbr -a mkd 'mkdir -p'
abbr -a ml 'mise list'
abbr -a mout 'mise outdated'
abbr -a mp mprocs
abbr -a mpr 'mise prune'
abbr -a mtr 'mise trust'
abbr -a mu multipass
abbr -a mup 'github-auth && mise upgrade'
abbr -a muse 'mise use'
abbr -a n nerdctl
abbr -a nas 'command ssh nas'
abbr -a o orbctl
abbr -a oco 'oco --fgm --yes'
abbr -a omp oh-my-posh
abbr -a p 'git add -A . && oco --fgm --yes'
abbr -a pf 'open -a "Path Finder"'
abbr -a pg 'pgrep -lf'
abbr -a ping gping
abbr -a pio platformio
abbr -a pk 'pkill -lf'
abbr -a pn pnpm
abbr -a pna 'pnpm add'
abbr -a pnd 'pnpm dev'
abbr -a pne 'pnpm exec'
abbr -a pni 'pnpm install'
abbr -a pnr 'pnpm run'
abbr -a pnx 'pnpm dlx'
abbr -a pp 'git add -A . && oco --fgm --yes && push'
abbr -a pping 'prettyping --nolegend'
abbr -a pr 'gh pr create --fill-verbose'
abbr -a pu pulumi
abbr -a qc quickcommit
abbr -a rimraf 'rm -rf'
abbr -a rmq 'xattr -d com.apple.quarantine'
abbr -a s skaffold
abbr -a sbrse 'sudo brew services'
abbr -a sf 'subl ~/.config/fish'
abbr -a sw switcher
abbr -a sm 'cd $HOME/src/github.com/synmux'
abbr -a synmux 'cd $HOME/src/github.com/synmux'
abbr -a t trunk
abbr -a ta 'cd $HOME/src/github.com/tecapps'
abbr -a task notion-task
abbr -a task-dev 'ruby -Ilib ./bin/notion-task'
abbr -a tc 'trunk check'
abbr -a tca 'trunk check -a'
abbr -a tcaf 'trunk check -a --fix'
abbr -a tdl 'tiddl download url'
abbr -a te 'tlm explain'
abbr -a tecapps 'cd $HOME/src/github.com/tecapps'
abbr -a tf terraform
abbr -a tfa 'trunk fmt -a'
abbr -a tfix trunkfix
abbr -a ti 'trunk init'
abbr -a tilde 'command ssh tilde'
abbr -a tower gittower
abbr -a ts 'tlm suggest'
abbr -a tu 'trunk upgrade'
abbr -a tw gittower
abbr -a ty 'open -a Typora'
abbr -a u upctl
abbr -a up 'github-auth && sudo chown -R dave:staff /opt/homebrew && topgrade && mise upgrade'
abbr -a v vue
abbr -a venv 'python -m venv'
abbr -a vi nvim
abbr -a vim nvim
abbr -a vue 'pnpm run vue'
abbr -a w wrangler
abbr -a y 'yt-dlp --cookies-from-browser chrome --remux-video mp4'
abbr -a zj zellij
