drwxr-xr-x@    - syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/.gemini\.gemini]8;;\
drwxr-xr-x@    - syn - 13 Jun 23:44 -I + main  ]8;;file:///Users/syn/.config/fish/.git\.git]8;;\
drwxr-xr-x@    - syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/.github\.github]8;;\
drwxr-xr-x@    - syn - 10 Jun 15:58 -- - -     ]8;;file:///Users/syn/.config/fish/.trunk\.trunk]8;;\
drwxr-xr-x@    - syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/bin\bin]8;;\
drwxr-xr-x@    - syn - 10 Jun 15:57 -M - -     ]8;;file:///Users/syn/.config/fish/completions\completions]8;;\
drwxr-xr-x@    - syn - 12 Jun 01:49 -- - -     ]8;;file:///Users/syn/.config/fish/conf.d\conf.d]8;;\
drwxr-xr-x@    - syn - 10 Jun 15:58 -- - -     ]8;;file:///Users/syn/.config/fish/functions\functions]8;;\
.rw-r--r--@  107 syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/.editorconfig\.editorconfig]8;;\
.rw-r--r--@  397 syn - 10 Jun 15:57 -- - -    󰊢 ]8;;file:///Users/syn/.config/fish/.gitignore\.gitignore]8;;\
.rw-r--r--@ 7.1k syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/abbrs.fish\abbrs.fish]8;;\
.rw-r--r--@ 2.2k syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/AGENTS.md\AGENTS.md]8;;\
.rw-r--r--@   74 syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/aliases.fish\aliases.fish]8;;\
.rw-r--r--@ 1.7k syn - 10 Jun 15:58 -- - -     ]8;;file:///Users/syn/.config/fish/atuin-ai.fish\atuin-ai.fish]8;;\
.rw-r--r--@ 7.1k syn - 13 Jun 23:48 -M - -     ]8;;file:///Users/syn/.config/fish/atuin.fish\atuin.fish]8;;\
lrwxr-xr-x@    - syn - 10 Jun 15:58 -- - -     ]8;;file:///Users/syn/.config/fish/AGENTS.md\CLAUDE.md]8;;\ -> AGENTS.md
.rw-r--r--@  538 syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/config.fish\config.fish]8;;\
.rw-r--r--@  826 syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/final.fish\final.fish]8;;\
.rw-r--r--@  419 syn - 10 Jun 15:57 -- - -    󰡯 ]8;;file:///Users/syn/.config/fish/fish_plugins\fish_plugins]8;;\
.rw-------   142 syn - 13 Jun 16:13 -I - -    󰡯 ]8;;file:///Users/syn/.config/fish/fish_variables\fish_variables]8;;\
.rw-r--r--@  26k syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/funcs.fish\funcs.fish]8;;\
.rw-r--r--  1.9k syn - 13 Jun 23:48 -M - -     ]8;;file:///Users/syn/.config/fish/interactive.fish\interactive.fish]8;;\
.rw-r--r--@ 1.1k syn - 10 Jun 15:57 -- - -     ]8;;file:///Users/syn/.config/fish/LICENSE\LICENSE]8;;\
.rw-r--r--@ 1.8k syn - 10 Jun 15:58 -- - -     ]8;;file:///Users/syn/.config/fish/os.fish\os.fish]8;;\
.rw-r--r--@ 2.7k syn - 10 Jun 15:57 -- - -    󰂺 ]8;;file:///Users/syn/.config/fish/README.md\README.md]8;;\
.rw-r--r--@ 7.1k syn - 10 Jun 15:58 -I - -     ]8;;file:///Users/syn/.config/fish/secrets.fish\secrets.fish]8;;\
.rw-r--r--@ 2.3k syn - 10 Jun 15:58 -- - -     ]8;;file:///Users/syn/.config/fish/vars.fish\vars.fish]8;;\
